---
# tasks file for haproxy
- name: install HAproxy
  package: 
    name: haproxy

- name: intall config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: 
  - reload haproxy service

- name: start service
  service:
    name: haproxy
    enabled: true
    state: started

- name: test
  include_tasks: tests.yml
  tags: tests