---
- hosts: load-balancers
  gather_facts: false
  become: true
  tasks:
    - name: install HAproxy
      package: 
        name: haproxy
    - name: intall config
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
    - name: start service
      service:
        name: haproxy
        enabled: true
        state: started
    - name: wait for haproxy to be ok on ports
      wait_for:
        port: "{{ item }}"
      with_items:
        - 80
        - 8080
    - name: ensure stat page is OK
      uri:
        url: http://127.0.0.1:8080/

- hosts: app-servers
  gather_facts: false
  become: true
  tasks:
    - name: install tomcat
      package:
        name: tomcat8
    - name: start tomcat
      service:
        name: tomcat8
        enabled: true
        state: started
    - name: wait for tomcat
      wait_for:
        port: 8080
    - name: test url and port
      uri:
        url: http://127.0.0.1:8080
        timeout: 240