---
- name: get running version
  uri:
    url: http://localhost:8080/{{ tomcat_app_name }}/version
    return_content: yes
    timeout: 30
  failed_when: false
  register: tomcat_app_predeploy_version

- name:
  set_fact:
    tomcat_need_deploy: "{{ tomcat_app_predeploy_version.status != 200 or tomcat_app_predeploy_version.json.version != tomcat_app_version }}"
    tomcat_need_deploy2: tomcat_app_predeploy_version.status!= 200 or (tomcat_app_predeploy_version.json.version != '{{tomcat_app_version }}')
    
- name: display vars
  debug:
    var: "{{ item }}"
  with_items:
    - tomcat_app_predeploy_version.status
    - tomcat_app_predeploy_version.json.version
    - tomcat_need_deploy | bool
    - tomcat_need_deploy
    - tomcat_need_deploy2
  tags: debug