- name: remove server from haproxy
  haproxy:
    backend: be_app_servers
    host: vm_{{ inventory_hostname|replace('.','_') }}
    state: disabled
    wait: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['load-balancers'] }}"